use_frameworks!

target 'MyCustomPod_Example', :exclusive => true do
  pod 'MyCustomPod', :path => '../'
end

target 'MyCustomPod_Tests', :exclusive => true do
  pod 'MyCustomPod', :path => '../'

  
end
